# CONFIGURACIÓN PARA EL AMBIENTE DE PRODUCCIÓN (RENDER)

# --- 1. CONFIGURACIÓN DEL DATASOURCE (Conexión a PostgreSQL) ---

# URL de conexión a la base de datos de Render. 
# Debe usar el prefijo 'jdbc:postgresql'
spring.datasource.url=jdbc:postgresql://dpg-d4fg69odl3ps73cud27g-a.virginia-postgres.render.com/eva3db

# Usuario proporcionado por Render
spring.datasource.username=usuario1

# Contraseña proporcionada por Render
spring.datasource.password=ydgcswllKPXRCSn12CsHQT9b9qZxghz8

# Driver de PostgreSQL
spring.datasource.driverClassName=org.postgresql.Driver

# Especifica el dialecto de PostgreSQL para que Hibernate genere el SQL correcto
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Control de la creación/actualización del esquema en la base de datos
# Usa 'update' para la primera subida; luego se recomienda cambiar a 'none' 
# cuando la estructura sea estable.
spring.jpa.hibernate.ddl-auto=update

# Opcional: Establece el perfil activo. Esto lo harás con una variable de entorno en Render,
# pero se puede usar para fines de prueba si es necesario.
# spring.profiles.active=prod