spring.application.name=demo
spring.datasource.url=jdbc:postgresql://dpg-d4fg69odl3ps73cud27g-a.virginia-postgres.render.com/eva3db
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=usuario1
spring.datasource.password=ydgcswllKPXRCSn12CsHQT9b9qZxghz8
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.h2.console.enabled=true

# Configuracion Keep-Alive y Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Desactivación de Seguridad para Actuator
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,\
org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration

# JPA DDL para ambiente local
spring.jpa.hibernate.ddl-auto=update